### ISSUE TITLE
When will this project code be open sourced?

### ISSUE THREAD

**Issue by samsdolphin** [hku-mars/MARSIM#1]
Dear authors, thanks for your great work. It's amazing!

May I know when you will open source this code? Thanks!

**Comment by Mealoore** [comment]
+1

**Comment by yewuya0206** [comment]
+1

**Comment by satyajitghana** [comment]
is there a video demo or paper linked with this ?

**Comment by RENyunfan** [comment]
> is there a video demo or paper linked with this ?

I just saw this on youtube: https://www.youtube.com/watch?v=hiRtcq-5lN0

**Comment by jackykongfz** [comment]
The code has been open sourced, thanks for your attention
