### ISSUE TITLE
预设轨迹进行仿真

### ISSUE THREAD

**Issue by XinZhaoDC** [hku-mars/MARSIM#15]
我尝试了采用RVIZ中的3D导航工具进行仿真测量。我想请教一下除了采用这种交互的方式，能否采用读取轨迹文件的方式让无人机按照预设轨迹（区别于控制导航算法）运行？谢谢！

**Comment by jackykongfz** [comment]
You can only run local_sensing&mars_drone_sim&odom_visualization nodes, and write a simple program to publish your trajectories' odometry to topic /quad_$(arg drone_id)/$(arg odom_topic) to simulate.

**Comment by XinZhaoDC** [comment]
好的，谢谢
