### ISSUE TITLE
Does the simulated point cloud have motion distortion?

### ISSUE THREAD

**Issue by jiejie567** [hku-mars/MARSIM#17]
Great work.  I wonder that whether the simulated point cloud have motion distortion. What's more, is it suitable for Point-LIO？

**Comment by jackykongfz** [comment]
It's a great question. For now. MARSIM do not support motion distortion, so the point cloud output may not suitable for PointLio.

**Comment by jiejie567** [comment]
Thx for your quick reply. I still have a question. If MARSIM does not support motion distortion, do I need to make modifications to the code related to distortion correction when running Fastlio?

**Comment by jackykongfz** [comment]
It's better if you turn off the distortion correction function in FASTLIO, but I think you can directly use the version supported for L515 of FASTLIO. cause this version do not have distortion correction function.

**Comment by jiejie567** [comment]
Thanks, wish you all the best!
