### ISSUE TITLE
Question about the number of maps

### ISSUE THREAD

**Issue by ChaselLau666** [hku-mars/MARSIM#18]
Thank you for your great work! This job seems to publish ten maps, but I only see 2 pcd files in the resource folder.
![image](https://github.com/hku-mars/MARSIM/assets/139679124/1ea1d52b-9484-4757-baec-e33cce31f1a3)

**Comment by jackykongfz** [comment]
Since the maps are large files that are not suitable for committing to the code, we upload the map files in the git repository's release files.

**Comment by ChaselLau666** [comment]
thank you for your great work
