### ISSUE TITLE
problem about use fast_lio2 by using data from MARSIM

### ISSUE THREAD

**Issue by 502006** [hku-mars/MARSIM#19]
Hi, i want to thank for your amazing work first.
I encounter a problem when trying to run fast_lio2 by using point cloud and imu data from MARSIM.
I already change the topic name in FAST_LIO/config/avia.yaml as follow  
<img width="670" alt="截圖 2023-12-20 下午5 42 08" src="https://github.com/hku-mars/MARSIM/assets/110392153/5d22da32-9d65-4139-9f97-83f7a88e47dc">
but point cloud data seem do not successfully connect to /laserMapping
<img width="1311" alt="截圖 2023-12-20 下午5 42 36" src="https://github.com/hku-mars/MARSIM/assets/110392153/4e035f8a-a192-4c03-94d9-754e01e981f1">
Thanks for your reply first.

**Comment by 502006** [comment]
if there anyone encounter the same problem?

**Comment by jackykongfz** [comment]
You should not directly connect the ros topic, since FASTLIO2's avia.yaml use /livox/lidar topic as input, its topic type is livox custom msg type, and the point cloud output by MARSIM is sensor_msgs/Pointcloud2.

**Comment by 502006** [comment]
Thanks for your reply. 
I try to modify Avia handler, but it seems that there’s no point.line and point.tag and point.offset_time in sensor_msgs/Pointcloud2.

**Comment by XinZhaoDC** [comment]
> You should not directly connect the ros topic, since FASTLIO2's avia.yaml use /livox/lidar topic as input, its topic type is livox custom msg type, and the point cloud output by MARSIM is sensor_msgs/Pointcloud2.

> Thanks for your reply. I try to modify Avia handler, but it seems that there’s no point.line and point.tag and point.offset_time in sensor_msgs/Pointcloud2.

I have the same question. The sensor_msgs/Pointcloud2 may be don't have each point’s timestamp which fast-lio2 needs. And It shows "failed to find match for field 'time'" when running fast-lio2. Just like the issue:https://github.com/hku-mars/FAST_LIO/issues/45.
And I failed to transform the sensor_msgs/Pointcloud2 to livox::CustomMsg. Can the author give some advice? Thx.
