### ISSUE TITLE
SLAM Algorithm used for Clouds used in MARSIM

### ISSUE THREAD

**Issue by satyajitghana** [hku-mars/MARSIM#2]
Hi,

The Points Clouds used in this project https://www.youtube.com/watch?v=hiRtcq-5lN0 look very clean and sharp. Which device was used to create these clouds? and which SLAM algorithm?

**Comment by jackykongfz** [comment]
We used a Livox AVIA LiDAR to scan the environment. FASTLIO2 and large-scale bundle adjustment algorithms are used to build the point cloud maps. Later I will provide a tutorial to construct a realistic point cloud map.
You can see some details of the implementation in the paper which is now available on Arxiv: https://arxiv.org/abs/2211.10716
