### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by fratopa** [hku-mars/MARSIM#5]
Hi! Thank you very much for having released the code! I was trying to build it but I got quite a few issues. 
The first one is regarding Eigen, the error was: `fatal error: Eigen/Core: No such file or directory`. I solved this one by changing every instance of `#include <Eigen/` to `#include <eigen3/Eigen/`.
Hoping to have solved this problem I am now presented with a new one I am not able to solve myself, in particular the error I now have is:
```
/home/my_username/marsim/src/MARSIM/local_sensing/src/pointcloud_render_node.cpp:1194:9: error: ‘size_’ not specified in enclosing ‘parallel’
 1194 | #pragma omp for
```
with many other like this all regarding the file `pointcloud_render_node.cpp`.
Do you have any suggestion on how to tackle it?

**Comment by linzs-online** [comment]
> Hi! Thank you very much for having released the code! I was trying to build it but I got quite a few issues. The first one is regarding Eigen, the error was: `fatal error: Eigen/Core: No such file or directory`. I solved this one by changing every instance of `#include <Eigen/` to `#include <eigen3/Eigen/>`. Hoping to have solved this problem I am now presented with a new one I am not able to solve myself, in particular the error I now have is:
> 
> ```
> /home/my_username/marsim/src/MARSIM/local_sensing/src/pointcloud_render_node.cpp:1194:9: error: ‘size_’ not specified in enclosing ‘parallel’
>  1194 | #pragma omp for
> ```
> 
> with many other like this all regarding the file `pointcloud_render_node.cpp`. Do you have any suggestion on how to tackle it?

Hi, I meet the same problem. Now I fixed this problem, my method is to comment 

> default(none)

in the local_sensing/src/pointcloud_render_node.cpp. There are **four such places** in this cpp file. Hoping to help you!

**Comment by fratopa** [comment]
OK, found another bug, in order to see the pointcloud coming from the sensor you also need to change every instance of `/world` into `world`

![image](https://user-images.githubusercontent.com/66642543/219961543-50929d97-e7ff-4d2c-a08f-fa7abec22030.png)

**Comment by fratopa** [comment]
For everyone having our same problems I created a [pull request](https://github.com/hku-mars/MARSIM/pull/6). While waiting for them to merge it you can clone my fork.

**Comment by jackykongfz** [comment]
Thanks for all the contributors above! Now we have a new branch supporting ubuntu20

**Comment by lilrookie76** [comment]
> Hi! Thank you very much for having released the code! I was trying to build it but I got quite a few issues. The first one is regarding Eigen, the error was: `fatal error: Eigen/Core: No such file or directory`. I solved this one by changing every instance of `#include <Eigen/` to `#include <eigen3/Eigen/`. Hoping to have solved this problem I am now presented with a new one I am not able to solve myself, in particular the error I now have is:
> 
> ```
> /home/my_username/marsim/src/MARSIM/local_sensing/src/pointcloud_render_node.cpp:1194:9: error: ‘size_’ not specified in enclosing ‘parallel’
>  1194 | #pragma omp for
> ```
> 
> with many other like this all regarding the file `pointcloud_render_node.cpp`. Do you have any suggestion on how to tackle it?

I also meet this error in ubuntu20 branch, and solved it by adding the variables into the "shared"
