### ISSUE TITLE
Can not get pointcloud from sensor in both branch

### ISSUE THREAD

**Issue by lilrookie76** [hku-mars/MARSIM#7]
![屏幕截图 2023-02-22 13:35:34](https://user-images.githubusercontent.com/57083481/220532295-11c5238d-06ae-4b25-ab76-083ad6087acd.png)
Hi, it seems like a transform problem, and I test it in both branches in ubuntu20.04 with the same result.

**Comment by Tomato1107** [comment]
> ![屏幕截图 2023-02-22 13:35:34](https://user-images.githubusercontent.com/57083481/220532295-11c5238d-06ae-4b25-ab76-083ad6087acd.png) Hi, it seems like a transform problem, and I test it in both branches in ubuntu20.04 with the same result.

You need to remove the "/" in the name behind frame_id in pointcloud_render_node.cpp

**Comment by jackykongfz** [comment]
Yeah, it seems like a transform problem that we have solved in the ubuntu20 branch. Make sure you have recompiled the code after changing to the ubuntu20 branch.

**Comment by lilrookie76** [comment]
Thank you all, it's actually solved in ubuntu20 branch. I just cloned the wrong branch. 

> Yeah, it seems like a transform problem that we have solved in the ubuntu20 branch. Make sure you have recompiled the code after changing to the ubuntu20 branch.
