### ISSUE TITLE
Tutorial to combine MARSIM with FUEL

### ISSUE THREAD

**Issue by lilrookie76** [hku-mars/MARSIM#8]
Hello!
Are there any points or suggestions for running FUEL in MARSIM? thanks.

**Comment by lilrookie76** [comment]
> 

Thanks for your great work!

**Comment by lilrookie76** [comment]
> The code has been pused to fuel_ubuntu20 branch.

Thank you very much for your work.

**Comment by YuHuan1021** [comment]
Hi, I obtain the errors when running FUEL by giving a 2D goal. What are the possible reasons? Thank you！

`[Kino replan]: start:        0        0 0.999998,            0            0 -3.02775e-06, 0 0 0, goal:3.28577 1.01509 2.32521, 0 0 0
open set empty, no path!
use node num: 1
iter num: 1
[ERROR] [1681387371.766770482]: search 1 fail
reach end
[ INFO] [1681387371.815682398]: Temp compute time = 0.025954, average compute time = 0.027016
[ INFO] [1681387371.919623821]: Temp compute time = 0.023773, average compute time = 0.026857
[ INFO] [1681387372.010617266]: Temp compute time = 0.020757, average compute time = 0.026680
[exploration_node-1] process has died [pid 8823, exit code -11, cmd /home/yu/Lidar_Exploration/MARSIM_FUEL/devel/lib/exploration_manager/exploration_node /odom_world:=/quad_0/lidar_slam/odom /map_ros/pose:=/quad0_pcl_render_node/sensor_pose /map_ros/depth:=/pcl_render_node/depth /map_ros/cloud:=/quad0_pcl_render_node/cloud __name:=exploration_node __log:=/home/yu/.ros/log/af51239a-d9f0-11ed-8984-4b255af90b58/exploration_node-1.log].
log file: /home/yu/.ros/log/af51239a-d9f0-11ed-8984-4b255af90b58/exploration_node-1*.log
[ INFO] [1681387372.150926664]: Temp compute time = 0.060093, average compute time = 0.028337
[ INFO] [1681387372.217346739]: Temp compute time = 0.026256, average compute time = 0.028428
[ INFO] [1681387372.363382218]: Temp compute time = 0.065813, average compute time = 0.029307
`

**Comment by YuHuan1021** [comment]
> Hi, I obtain the errors when running FUEL by giving a 2D goal. What are the possible reasons? Thank you！
> 
> `[Kino replan]: start: 0 0 0.999998, 0 0 -3.02775e-06, 0 0 0, goal:3.28577 1.01509 2.32521, 0 0 0 open set empty, no path! use node num: 1 iter num: 1 [ERROR] [1681387371.766770482]: search 1 fail reach end [ INFO] [1681387371.815682398]: Temp compute time = 0.025954, average compute time = 0.027016 [ INFO] [1681387371.919623821]: Temp compute time = 0.023773, average compute time = 0.026857 [ INFO] [1681387372.010617266]: Temp compute time = 0.020757, average compute time = 0.026680 [exploration_node-1] process has died [pid 8823, exit code -11, cmd /home/yu/Lidar_Exploration/MARSIM_FUEL/devel/lib/exploration_manager/exploration_node /odom_world:=/quad_0/lidar_slam/odom /map_ros/pose:=/quad0_pcl_render_node/sensor_pose /map_ros/depth:=/pcl_render_node/depth /map_ros/cloud:=/quad0_pcl_render_node/cloud __name:=exploration_node __log:=/home/yu/.ros/log/af51239a-d9f0-11ed-8984-4b255af90b58/exploration_node-1.log]. log file: /home/yu/.ros/log/af51239a-d9f0-11ed-8984-4b255af90b58/exploration_node-1*.log [ INFO] [1681387372.150926664]: Temp compute time = 0.060093, average compute time = 0.028337 [ INFO] [1681387372.217346739]: Temp compute time = 0.026256, average compute time = 0.028428 [ INFO] [1681387372.363382218]: Temp compute time = 0.065813, average compute time = 0.029307 `

I have solved this problem by installing the officially provided [nplot](https://github.com/stevengj/nlopt) library after removing `ros - * - nplot`!
